### ISSUE TITLE
error KeyError: '_module'

### ISSUE THREAD

**Issue by max326-coder** [stanfordnlp/wge#11]
PS C:\Users\Dhaval\Downloads\uds-master> python3 uds.py push ~\Desktop\ffmpeg.exe
Traceback (most recent call last):
  File "uds.py", line 534, in <module>
    main()
  File "uds.py", line 452, in main
    uds = UDS()
  File "uds.py", line 46, in __init__
    self.api = GoogleAPI()
  File "C:\Users\Dhaval\Downloads\uds-master\api.py", line 19, in __init__
    self.reauth()
  File "C:\Users\Dhaval\Downloads\uds-master\api.py", line 25, in reauth
    credentials = store.get()
  File "C:\Users\Dhaval\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\oauth2client\client.py", line 407, in get
    return self.locked_get()
  File "C:\Users\Dhaval\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\oauth2client\file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "C:\Users\Dhaval\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\oauth2client\client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'

help me please reply me please

**Comment by ezliu** [comment]
I'm not sure what this `uds.py` script you're running is. I do notice that you're using Python3 and this code is written for Python2.

**Comment by max326-coder** [comment]
No, I am using Python 3 and using python 3 code
check this https://developers.google.com/drive/api/v3/quickstart/python
also this https://youtu.be/5Z-95U0wIMw?list=WL

I am doing what is told in this, but this error #11 comes in the last


can anyone help me

**Comment by ezliu** [comment]
Sorry, this is not related to this project
